### ISSUE TITLE
Nodes without an FQDN cause the server recipe to fail

### ISSUE THREAD

**Issue by btm** [jesseadams/munin#35]
Need to delete an nodes that don't have fqdn since that's what we sort by. Granted, you should make sure your nodes have an fqdn, but it'd be nice if it didn't break your munin server.

https://github.com/augieschwer/munin/commit/881de2c45d13b61345aceff6ec752a2be716be1d

https://tickets.opscode.com/browse/COOK-3177

**Comment by jesseadams** [comment]
Thanks for the report @btm. I'll check this out soon.

**Comment by jesseadams** [comment]
it looks like this references a very old commit. The current version of the cookbook references hostnames instead of fqdns.

**Comment by kampfschlaefer** [comment]
?

The current version uses node[:fqdn] to reference clients and node[:ipaddress] to access them. If either is missing, it fails horribly. (And it doesn't work on nodes with ipv6address but not ipaddress...)

**Comment by jacobvosmaer** [comment]
This bit me too today. I worked around it by making sure the node without an FQDN got one after all.

**Comment by jacobvosmaer** [comment]
cookbook version 1.4.3, nodes running a mix of Chef 11/12, Chef Server 12.
